### ISSUE TITLE
Flarum

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#10] opened 2023-07-11 20:24 UTC
Flarum is a technically advanced, open and extensible discussion platform. Flarum aims to bring people interaction to a new level by how it is designed and engineered.

- [NLnet project](https://nlnet.nl/project/Flarum)
- [source code](https://github.com/flarum/framework)

This project is very much alive, with a large user base, and not packaged anywhere. Providing a turnkey service module for self-hosting is a high-value target.

**Comment by albertchae** [comment] 2023-07-18 22:46
@ngi-nix/moss is claiming this

**Comment by jasonodoom** [comment] 2023-07-21 00:55
We used [composer2nix](https://github.com/svanderburg/composer2nix) on the output of `composer create-project flarum/flarum.`  for [installing flarum](https://docs.flarum.org/install/#installing) because `composer.lock` isn't checked into the flarum repo.  

We need to find a way to include `composer.lock` into the sources.

**Comment by fricklerhandwerk** [comment] 2023-07-21 07:57
Not sure why you would need to merge sources for that. `composer2nix` has to be run manually, otherwise you'll have [IFD](https://github.com/NixOS/nix/pull/7332/files#diff-6ed75e4585860a7666b367cc189077f970429de6f551a2b6727e75b1ee153a4c).

What you *may* want instead – but I may be wrong – is a helper script in the devshell that checks out the source into a tempfile, runs `composer create-project flarum/flarum .`, runs `composer2nix` on the output, and overwrites the generated Nix expressions. And of course some documentation what to do when and why. I don't know what the code generated by `composer2nix` looks like, please open a PR with what you have so far if you need more input.

**Comment by albertchae** [comment] 2023-07-21 13:53
@fricklerhandwerk Oh also, do you have a contact at the flarum project in case we have additional questions or do you recommend just opening an issue on their repo? No one in our mob is that familiar with the php ecosystem and their best practices, so being able to get more context would be helpful.

**Comment by fricklerhandwerk** [comment] 2023-07-21 15:00
> is the helper script you're suggesting something we'd run manually when we need to update `pkgs/flarum` in this repo? Or is it something that'd run as part of building the flarum package?

Yes, it would have to be run manually. As said, it will be IFD if you make it part of the build, because you'll first have to realise the derivation with the source definitions before you can continue evaluating the actual package definition.

**Comment by albertchae** [comment] 2023-07-25 00:59
**Disclaimer: braindump for @ngi-nix/moss , please ignore if you're not in @ngi-nix/moss**

Notes from July 24 mob session:

- We found a closed PR from several years ago on nixpkgs that attempted to package `flarum` and saw what we could learn from it https://github.com/NixOS/nixpkgs/pull/96869
  - One thing they did is distinguish between modules and packages. It probably makes sense to make a module for flarum because we need to configure nginx and other runtime dependencies.
  - Their filesystem hierarchy
  - They commit `composer.json` and `composer.lock` and use them while packaging flarum
  - We weren't able to `nix build .#flarum` when checking their branch.
- Our next idea was to identify success examples of using composer2nix to add packages to nixpkgs. We found:
  - [pixelfed](https://github.com/NixOS/nixpkgs/tree/dfcffbd74fd6f0419370d8240e445252a39f4d10/pkgs/servers/web-apps/pixelfed)
  - [bookstack](https://github.com/NixOS/nixpkgs/tree/dfcffbd74fd6f0419370d8240e445252a39f4d10/pkgs/servers/web-apps/bookstack)
  - [snipe-it](https://github.com/NixOS/nixpkgs/tree/dfcffbd74fd6f0419370d8240e445252a39f4d10/pkgs/servers/web-apps/snipe-it)
  - All of these packages are almost the same except for the shell commands in the install phase of `default.nix`.
    - Side note: These packages include an [`update.sh`](https://github.com/NixOS/nixpkgs/blob/7482a0e6ef6c53539467df143d825a9545eacf67/pkgs/servers/web-apps/pixelfed/update.sh) which seems to be used to make bumping the `composer.lock` and version number more convenient. We are choosing to ignore this for now.
- We were able to copy this structure and get to the point where we got an error with `composer.json` not matching `composer.lock`
  ```
       > - Required package "flarum/nicknames" is not present in the lock file.                               
       > - Required package "flarum/pusher" is not present in the lock file.                                  
       > - Required package "flarum/statistics" is not present in the lock file.                              
       > - Required package "flarum/sticky" is not present in the lock file.                                  
       > - Required package "flarum/subscriptions" is not present in the lock file.                           
       > - Required package "flarum/suspend" is not present in the lock file.                                 
       > - Required package "flarum/tags" is not present in the lock file.                                    
       > This usually happens when composer files are incorrectly merged or the composer.json file is manually
 edited.
```
- We believe this is happening because the `flarum/flarum` repo does not have a `composer.lock` checked in and `composer2nix` [generates a stub `composer.lock](https://github.com/svanderburg/composer2nix/blob/299caca4aac42d7639a42eb4dde951c010f6e91c/src/Composer2Nix/composer-env.nix#L168-L178)

- We obtained a `composer.lock` by running `composer create-project flarum/flarum .` as recommended by  https://docs.flarum.org/install/#installing. We also tested that the generated `composer.lock` is the equivalent of running `composer install` in a checkout of `flarum/flarum`. (We also tried deleting the `vendor` directory before running `composer2nix` to make the process pure, which produced the same file with no warning.
- `composer.lock` seems to be intentionally git ignored and not checked into `flarum/flarum`
  - https://github.com/flarum/flarum/commit/995a2621db714604983c892eaef2653fe3d425e2
    - This appears to be the reason https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/#tip-%236%3A-put-%60composer.lock%60-into-%60.gitignore%60-in-libraries
  - https://github.com/flarum/flarum/commit/ea61c2255657d722fab462c8ba443db6bca3a699
- Our conclusion so far is that users are using `flarum/flarum` as a template by creating a project based on it, and then committing the lock file on their created project. This seems to be a supported pattern https://getcomposer.org/doc/03-cli.md#create-project. It seems `composer2nix` does not support projects with missing `composer.lock` files ([see issue](https://github.com/svanderburg/composer2nix/issues/34)). So we should either modify `composer2nix` to handle that or modify the generated code or add something later to overlay (not necessarily the nix overlay) our `composer.lock` on top of `flarum/flarum`.

**Comment by cleeyv** [comment] 2023-07-25 04:18
> I just assume we don't want IFD in a monorepo, as the repo's expression may grow arbitrarily large and we'd quickly run into issues with evaluation time. Right, @cleeyv?

Yes, my work on the CI is quickly surfacing problems with IFDs since there is already one there for mach-nix in the liberaforms package. There are evaluation-time performance impacts, as you say, but also other problems (issue coming soon). I understand why nixpkgs doesn't allow them and I think it could be prudent to consider this rule for ngipkgs as well.

@albertchae while you're considering options for packaging Flarum, you may want to check out this PR on nixpkgs for a new builder for PHP Composer-based applications: https://github.com/NixOS/nixpkgs/pull/225401 It is marked as a draft, but reading the comments it sounds like it is pretty late in the process, and ready to be tested. It would be cool if you could use Flarum to do a test of this the builder and give feedback for the PR review process. And even if you don't test it out, the comments on the PR seem like they could provide relevant background info for your work on the Flarum packaging.

**Comment by albertchae** [comment] 2023-07-25 05:33
@cleeyv Thanks! Coincidentally we also came across https://github.com/NixOS/nixpkgs/pull/225401 right after we wrote our brain dump, so trying that out will probably be the focus of our remaining mob sessions this week.

**Comment by DMills27** [comment] 2023-07-26 00:57
**Disclaimer: braindump for https://github.com/orgs/ngi-nix/teams/moss , please ignore if you're not in https://github.com/orgs/ngi-nix/teams/moss**

After realising that composer2nix doesn't composer.lock as well, we decided upon the builder from [this PR](https://github.com/NixOS/nixpkgs/pull/225401).  We created a second branch `moss-flarum-2` to try this approach. This has a number of .nix files that can be found in [this commit](https://github.com/ngi-nix/ngipkgs/commit/45f433c43eb561c1dee2107f113d664e18ccc889). We had to modify a namespaces in order to get it running, more specifically `phpDrv`and `php`in order to get it to build. Also, in [this PR](https://github.com/ngi-nix/ngipkgs/commit/9cdba8674ff1a633d023291fcd825c1e39e05b3c) the `callPackages` function was defined in the same way and we're currently not sure why it worked but it did. 

We followed the pattern of `wp-cli` and others, where a `composer.lock` file was generated and checked into the Nix build directory and then successfully built the flarum package.

**Comment by cleeyv** [comment] 2023-07-27 19:24
Cross-posted from a parallel conversation over in issue #24:

>  So we haven't explicitly been testing whether flarum is compatible with darwin (but also there's no reason it shouldn't be compatible? we just haven't tried).

Based on a quick look through the flarum documentation, I get the impression that in theory it could be run on MacOS but since that server hardware is relatively rare/expensive, practically it is much more likely to be run in production on linux. However, since MacOS is way more common for dev machines, they do mention in their section on [Development Tools](https://docs.flarum.org/contributing/#development-tools) the use of tools like [Laravel Valet](https://laravel.com/docs/master/valet) to do local dev on Flarum. Based on this, I can imagine the usefulness of a dev shell / local deployment config of some kind for darwin. Though it also sounds like you've already been supporting that use case on x86_64-linux with lima which maybe is simpler. I'm curious to hear if you have further thoughts on this (I'm going to cross-post this over to the flarum issue as well).

**Comment by cleeyv** [comment] 2023-07-28 05:06
> since ngipkgs doesn't seem to include a testing framework (related? https://github.com/ngi-nix/ngipkgs/issues/28) e.g. home-manager, we decided to enable the service on a live NixOS system

Yes, seeing if we can get NixOS tests working on our hydra instance is one of the top priorities for further improvement to ngipkgs. The timing is unfortunate that I'm going to be away for the next two weeks so won't be able to work on it soon, but there should be progress on this later in August. 

> (lots of flailing with a morph DigitalOcean image that ended up at a dead end because of flakes incompatibility)

When I was a Summer of Nix participant in past years, we did this kind of flake deployment to digital ocean using deploy-rs and it worked pretty well. The main difference is that at that time each project had its own repo and flake, so a similar use of deploy-rs would still need to be tested on ngipkgs. I created an issue for work on this: https://github.com/ngi-nix/ngipkgs/issues/22.

> we decided to reference the existing module (liberaforms) defined in ngipkgs, which when initialized the same way, fails with the same error.

When it was in its own liberaforms-flake repo, we deployed liberaforms in two ways: with deploy-rs to digital ocean, and with nixos-container to a local container. On the old repo, these two methods are documented here: https://github.com/ngi-nix/liberaforms-flake/tree/main/docs

Since the migration to ngipkgs, so far we have only implemented deployment with nixos-container, and that is confirmed to be working. Well, there is currently some error with liberaforms when deployed to a local container (the web app doesn't properly load in the browser), but it is an error page that is generated by liberaforms so we know the build and deployment and system configuration aspects are all working at least. 

An advantage of trying to do the same kind of nixos-container deployment with flarum as well is that you could more directly model it on the currently working liberaforms example in ngipkgs.

> is a separate repository for flarum correct? following the example of https://github.com/ngi-nix/liberaforms-flake (although we may not understand the context behind this repo.)

A separate repository for each project was the old way things were organized for nix packaging at NGI, and for Summer of Nix. This year it was decided to consolidate all of the packaging work into a single monorepo, ngipkgs. Your use of it here for flarum is experimental, and we're all learning along the way. As the the program progresses, these questions of how to use ngipkgs will become more clear.

**Comment by cleeyv** [comment] 2023-08-20 22:10
I see that moss is working on this again in https://github.com/ngi-nix/ngipkgs/tree/moss-flarum-module-rebased-on-pretalx , that you were previously trying to do testing with a deploy-rs to a cloud instance (as discussed in #22), and that algae has shared their local testing approach using nixos-test (#28). I will just add that nixos-container is another option that can be used for a similar kind of local testing and the `configs/liberaforms/containers.nix` is available as a template. If you have any questions about this approach to local testing, let me know.

**Comment by Chickensoupwithrice** [comment] 2023-09-07 01:58
We're working on getting the Flarum module running. 
Currently we decided to have `nginx` own the directory from which flarum is run. In order to set this up we have a systemd oneshot script. Previously, the `users.user` config was creating a flarum user, and setting it's home directory to be `cfg.stateDir` which had the side effect of creating this directory with flarum permissions. 
Now we want to create this directory with nginx permissions, however when we removed the `users.user` config option, the oneshot script no longer executes at all. 
One very crude solution to this could be running the systemd script as user root, and having that `chown` the directory. We would much prefer that the systemd oneshot script (which is being run as nginx) also create the directory. When manually run, the systemd unit does what we expect, but we're unable to get it to start on boot/login

**Comment by lorenzleutgeb** [comment] 2023-09-07 08:13
FWIW, instead of fiddling around with permissions explicitly, consider the following options:

 * [`RuntimeDirectory=, StateDirectory=, CacheDirectory=, LogsDirectory=, ConfigurationDirectory=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=)
 * [`DynamicUser=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=)
 * [Capabilities](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities)
 * [Credentials](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Credentials)

**Closed** 2023-09-15 01:52 UTC
Labels: package, service, NGI0 Entrust

**Comment by albertchae** [comment] 2023-09-15 01:56
Turns out https://github.com/ngi-nix/ngipkgs/issues/10#issuecomment-1709351915 was a red herring due to the install oneshot service running multiple times due to downstream services failing and retrying

**Comment by albertchae** [comment] 2024-05-20 07:26
flarum has been upstreamed to nixpkgs in https://github.com/NixOS/nixpkgs/pull/311608/ so it should also be a candidate for https://github.com/ngi-nix/ngipkgs/issues/76
